---
title:
- type: main
  text: An Adventurer from Hudson Bay
- type: subtitle
  text: Journal of Matthew Cocking. From York Factory to the Blackfeet Country, 1772-73.
- type: extended
  text: The Royal Society of Canada, 1908
creator:
- role: author
  text: Matthew Cocking
- role: editor
  text: Lawrence J. Burpee
rights: © 2021 Public domain
...
